### ISSUE TITLE
Windows 11 23H2 - Imported to 22H2

### ISSUE THREAD

**Issue by henrybelk** [alaurie/WimWitchFK#12]
Once I import a 23H2 ISO, under .\WimWitchFK-main\imports, it creates sub-directories for 22H2. The _.\WimWitchFK-main\updates\Windows 11_ folder correct creates 23H2 folders after downloading updates.

Got an error when trying to run. Renamed _.\WimWitchFK-main\imports\DotNet\Windows 11\22H2_ and _.\WimWitchFK-main\imports\iso\Windows 11\22H2_ to 23H2 and it works now.

```
11/02/2023 14:12:48 Information - Checking to see if the staging path exists...
11/02/2023 14:12:48 Information - The path existed, and it has been purged.
11/02/2023 14:12:48 Warning - .Net 3.5 Binaries are not present for 23H2
11/02/2023 14:12:48 Warning - Import .Net from an ISO or disable injection to continue
```

```
11/02/2023 14:23:58 Information - D:\WimWitchFK-main\Mount
11/02/2023 14:28:17 Warning - ISO Binaries are not present for Windows 11 23H2
11/02/2023 14:28:17 Warning - Import ISO Binaries from an ISO or disable ISO/Upgrade Package creation
11/02/2023 14:28:17 Error - Discarding WIM and not making it so
```

**Comment by alaurie** [comment]
Thanks for this, its now been resolved into the main branch. You can download and run again.

https://github.com/alaurie/WimWitchFK/commit/d71e1d7dd93e90d3ac9a3f3313f32fdcd0ab66bc

**Comment by The1andONLYTLC** [comment]
Still seeing 23H2 import as 22H2 on the newest build. Using the latest 23H2 from February.
